### ISSUE TITLE
[Forge 1.20.1] Crash when Opening Preview Screen

### ISSUE THREAD

**Issue by Talan67** [caeruleusDraconis/world-preview#1]
When going to create a world and clicking onto the preview tab the game crashes. I have a pretty big mod list so if needed I can slowly go through them all and see if another mod is causing the crash, but heres the log for now:

[latest.log](https://github.com/caeruleusDraconis/world-preview/files/12156458/latest.log)

**Comment by caeruleusDraconis** [comment]
Looks like the incompatible mod is WorldEdit. Could you please confirm if this is the case? If there is another crash without WorldEdit, please attatch the new log file again.

**Comment by caeruleusDraconis** [comment]
Could you please check if this fixes the issue:

[world_preview_1.0.1.tar.gz](https://github.com/caeruleusDraconis/world-preview/files/12162314/world_preview_1.0.1.tar.gz)

**Comment by caeruleusDraconis** [comment]
GitHub closed this issue automatically with my commit. Please reopen if there are still problems.
