### ISSUE TITLE
crashes with 'better nether/better end' mod(s)

### ISSUE THREAD

**Issue by Aces-and-Jacks** [caeruleusDraconis/world-preview#10]
https://mclo.gs/1ZyJKLR

I know that more culling and cull less leaves say it isn't compatible but that isn't it. Maybe the better nether mod but don't know

**Comment by AlienXtream** [comment]
does seem to be incompatible with the betterx mods. just got this too. i recommend changing the name to "crashes with 'better nether/better end' mod(s)"
dont actually know if it crashes with better end but given they are very much the same sort of thing for their respective dimensions (and made by the same developers) it's a reasonable assumption that it would crash too

**Comment by Taiterio** [comment]
This bug has been fixed in [Release 1.1.2](https://modrinth.com/mod/world-preview/version/nSPYf7G7)

If the issue persists in that release, please reopen the issue.
