### ISSUE TITLE
Map doesn't show on world creation on the Medieval MC modpack

### ISSUE THREAD

**Issue by Aces-and-Jacks** [caeruleusDraconis/world-preview#12]
Not sure what causes it yet but for some reason the map preview doesn't load when creating a new world. It does show when the world is generated

**Comment by caeruleusDraconis** [comment]
I managed to narrow down the incompatibility to [Biolith](https://github.com/gniftygnome/Biolith).

@Aces-and-Jacks It would be nice if you could provide a link to the modpack next time :)

**Comment by Aces-and-Jacks** [comment]
Oh sorry, I haven't made much issues about modpacks so I didn't think about adding a link. Thank you for solving what caused the issue, and maybe fixing it

**Comment by caeruleusDraconis** [comment]
Should be fixed with version `1.1.3`: https://modrinth.com/mod/world-preview/version/8myO4JQ4

Feel free to reopen if your problem isn't fixed.
