### ISSUE TITLE
Is it compatible with the terrain added to the datapack

### ISSUE THREAD

**Issue by ABKQPO** [caeruleusDraconis/world-preview#13]
Like [Terralith](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/), [Nullscape](https://www.planetminecraft.com/data-pack/nullscape/) and [Amplified Nether](https://www.planetminecraft.com/data-pack/amplified-nether-1-18/) datapacks

**Comment by caeruleusDraconis** [comment]
Yes, it is compatible with datapacks.

Feel free to reopen if you run into any issues with datapacks specifically.
