### ISSUE TITLE
关于性能问题 about performance

### ISSUE THREAD

**Issue by HMwancheng** [caeruleusDraconis/world-preview#15]
打开界面，关闭后，即使没有在mod，仍然会消耗cpu（即使没有查看）/‘
when open world-preview GUI, and then closed, even mod not in use, it still will use CPU
<img width="1110" alt="image" src="https://github.com/caeruleusDraconis/world-preview/assets/91036325/b8dc6bd9-eb07-413e-a8ac-12ac123583e0">
![image](https://github.com/caeruleusDraconis/world-preview/assets/91036325/f34f9482-6f9d-4acb-860a-a5278e5b4666)

**Comment by Taiterio** [comment]
Thank you for the report! 
The issue has been fixed and there will be another update following shortly after the release of MC 1.20.3. 

Only the in-game preview was affected, the one in the main menu was unaffected by this bug.

**Comment by HMwancheng** [comment]
did will update for MC 1.20.1?

**Comment by caeruleusDraconis** [comment]
Yes, there will be 1.1.4 release for all versions.
