### ISSUE TITLE
Mod Compatibilty Issue?

### ISSUE THREAD

**Issue by Gantros** [caeruleusDraconis/world-preview#18]
I added a couple new mods, and I am getting a World Preview error, suggesting an incompatible mod. The new mods I added were WF's Cave Overhaul, Better Archaeology, and Regional Ore Veins along with its core library and Create add-on patch. This is for MC 1.20.1, Forge 47,2,6.

**Comment by caeruleusDraconis** [comment]
Should be fixed with the next release. Could you plese test if [this world_preview-1.zip build](https://github.com/caeruleusDraconis/world-preview/files/13696101/world_preview-1.zip) fixes the issue?

The file is compressed because GitHub doesn't allow attaching JAR files directly :(

**Comment by Gantros** [comment]
The issue was the cave overhaul, and unfortunately that mod conflicted with other mods in my pack so I removed it. But thanks for addressing the issue.

**Comment by caeruleusDraconis** [comment]
The fix is now released with 1.1.5.
