### ISSUE TITLE
Memory Leak when opening preview menu in existing world. 

### ISSUE THREAD

**Issue by Apothicon02** [caeruleusDraconis/world-preview#21]
### What happened?

When opening the preview menu while in an already loaded world, it will trigger a memory leak that crashes the game within minutes. 

### Minecraft Version

1.20.1

### Modloader (Fabric/Forge)

Forge

### World-Preview Version

1.1.5

### Minecraft Logs

https://gist.github.com/Apothicon02/d5ea570f104f6cc05c240d2768fe7203

### Additional Information

Happens even if I uninstall sinytra connector.

**Comment by caeruleusDraconis** [comment]
Thanks, for creating the issue.

Sadly, I am unable to reproduce this bug with just forge and World Preview. So, it is likely a compatibility issue with (at least) one of your other installed mods.

Are you using a public mod pack? If not, could you please try to narrow down this behavior to a more manageable list of mods (or even better a specific mod)?
