### ISSUE TITLE
Saving A preview of a world

### ISSUE THREAD

**Issue by OatmealRaisins** [caeruleusDraconis/world-preview#23]
### Feature Request

Hello! Is it possible to implement a save system to the preview, where the map doesn't restart after exiting? Similar to Xaero's world map mod where it saves each chunk you load, so you could view it at a later time. Unfortunately since my system isn't the fastest, a normal preview might take up to half an hour to load in fully, and all that progress is lost right after exiting the preview. 
Thanks!

**Comment by caeruleusDraconis** [comment]
This feature is implemented with Version 1.2.0 and can be enabled / disabled in the settings. Let me know if there are any problems.
