### ISSUE TITLE
Incompatible with Biome Spawn Point

### ISSUE THREAD

**Issue by ultimatejacob27** [caeruleusDraconis/world-preview#26]
### What happened?

When loading the world preview before creating a world, if Biome Spawn Point is installed, the map fails to load and gives an error message.

### Minecraft Version

1.20.1

### Modloader (Fabric/Forge)

Fabric

### World-Preview Version

1.2.1

### Minecraft Logs

Log was too long to paste. I was using a large modpack.

### Additional Information

https://www.curseforge.com/minecraft/mc-mods/biome-spawn-point
There are a lot of mods in the modpack but Biome Spawn Point made the difference. World Preview works without it.

**Comment by mensinda** [comment]
What modpack are you using? I am unable to reproduce this with just biomespawnpoint-1.20.1-2.2.jar and collective-1.20.1-7.32.jar on fabric alone.

Could you please upload the log file to https://pastebin.com/ or, even better, attach it to a GitHub comment directly:

![tmp](https://github.com/caeruleusDraconis/world-preview/assets/3407462/f2e6ef5a-8f03-4524-9f83-4570de89dca3)

**Comment by caeruleusDraconis** [comment]
What modpack are you using? I am unable to reproduce this with just biomespawnpoint-1.20.1-2.2.jar and collective-1.20.1-7.32.jar on fabric alone.

Could you please upload the log file to https://pastebin.com/ or, even better, attach it to a GitHub comment directly:

![tmp](https://github.com/caeruleusDraconis/world-preview/assets/3407462/f2e6ef5a-8f03-4524-9f83-4570de89dca3)
