### ISSUE TITLE
Copy coordinates with TP command to clipboard.

### ISSUE THREAD

**Issue by KateReller** [caeruleusDraconis/world-preview#27]
### Feature Request

When hovering over a spot on the world preview, right clicking should copy the coords to your clipboard along with a TP command. 
Inspired by a similar world previewer tool: https://map.jacobsjo.eu/

**Comment by Taiterio** [comment]
This feature has been implemented and will be included in Release 1.2.2, thank you for the suggestion!

The implementation places the coordinates "X Y Z" into your clipboard, after which you can paste it into the commands of your choice. In cases where the y-value is unknown/undefined, a "~" will be inserted instead to keep you at the same height.
