### ISSUE TITLE
Add interface access directly in game

### ISSUE THREAD

**Issue by craftish37** [caeruleusDraconis/world-preview#3]
This mod would be a perfect fit for any vanilla player wanting to discover their world by other means and it would be sweet to have access to the previewer while the game is running

**Comment by caeruleusDraconis** [comment]
This should be technically possible (at least for single player) and nice to have, but I won't make any promises.

**Comment by caeruleusDraconis** [comment]
Implemented for single-player worlds. Multiplayer won't happen, since there isn't even a reliable way for getting the seed from the server...

**Comment by craftish37** [comment]
Well there are some _pretty reliable ways_ to get the seed but might not be tolerated everywhere 👀

However, for servers that give the seed to players, it might still be interesting to be able to access the panel, even without pre-inserted seed

Anyway, thanks again for this feature 😄
