### ISSUE TITLE
Hide World Preview Button in Options Menu

### ISSUE THREAD

**Issue by nco2k** [caeruleusDraconis/world-preview#30]
### Feature Request

would be cool to have a setting to hide the world preview button in the options menu.

**Comment by Taiterio** [comment]
This is already present, in the first tab of the options menu, the bottom left option "Show button in menu" can be toggled to turn off the preview button! :)

**Comment by nco2k** [comment]
oh wow i didnt even know there was a settings menu. any chance you could do a modmenu integration? im used to getting to the mods settings through modmenu.
