### ISSUE TITLE
The preview is weirdly streched out and the player icon is moving weirdly

### ISSUE THREAD

**Issue by Rhgx** [caeruleusDraconis/world-preview#31]
### What happened?

I just recently downloaded this mod and have come across this issue where when I open the preview screen the screen would be weirdly streched out and didn't show the player icon correctly when I dragged the map around. I'll be uploading my finding to streamable as there is a file size limit of 10MB on github. 

### Minecraft Version

1.20.1

### Modloader (Fabric/Forge)

Fabric

### World-Preview Version

1.2.2

### Minecraft Logs

https://mclo.gs/0macMZi

### Additional Information

https://streamable.com/h4wui4

**Comment by caeruleusDraconis** [comment]
Thank you for providing a video to showcase this bug. What zoom level are you using (looks like fully zoomed in)?

Sadly, I am unable to reproduce this on my end with version 1.2.2 (with any zoom level). Would it be possible for you to share the modpack you are using?
