### ISSUE TITLE
Noise view and Noise Router info

### ISSUE THREAD

**Issue by SettingDust** [caeruleusDraconis/world-preview#35]
### Feature Request

Helpful for data pack developing

**Comment by caeruleusDraconis** [comment]
Could you please provide a bit more information on what exactly you want? What is `Noise view and Noise Router info`? Do you have examples?

I am not familiar with data pack development. I just [call a function](https://github.com/caeruleusDraconis/world-preview/blob/1.20/src/main/java/caeruleusTait/world/preview/backend/worker/SampleUtils.java#L394-L399) with a block position, and it tells me the biome.

**Comment by SettingDust** [comment]
Noise router is the info in F3 that decide the terrain and biomes.
https://minecraft.wiki/w/Noise_router
![图片](https://github.com/caeruleusDraconis/world-preview/assets/19922286/ac9f4b01-1278-4ce9-89a5-76c57598963f)
https://minecraft.wiki/w/Debug_screen
https://minecraft.wiki/w/World_generation#Biomes

Noise view is showing the noise value that can get the sampler from `Chunk#getOrCreateChunkNoiseSampler`
The result should looks like https://misode.github.io/worldgen/noise/?version=1.21 and https://minecraft.wiki/w/File:Biome_and_density_functions.png
![图片](https://github.com/caeruleusDraconis/world-preview/assets/19922286/c69b81d1-358c-47e8-b52b-d6d0bc1440d8)

EDIT: For reference, there is a gamerule in https://modrinth.com/mod/worldgen-devtools to generating noise only

**Comment by caeruleusDraconis** [comment]
So, if I understand you correctly, this would mean Adding the F3 noise router info to the hover info and adding new "heightmap" views for each noise function?

**Comment by SettingDust** [comment]
> So, if I understand you correctly, this would mean Adding the F3 noise router info to the hover info and adding new "heightmap" views for each noise function?

More or less. Looks like `NoiseRouter` includes all the info needing to calc

**Comment by caeruleusDraconis** [comment]
This is now implemented in version 1.3.0

**Comment by SettingDust** [comment]
For anyone can't see the values. The tooltip is controlled by language. The english will show the values
