### ISSUE TITLE
Littering the logs + black regions on the ungenerated regions

### ISSUE THREAD

**Issue by frosthuuuund** [caeruleusDraconis/world-preview#41]
### What happened?

![image](https://github.com/user-attachments/assets/53e5326b-8a98-49dd-aa62-ee6d1556f993)

### Minecraft Version

1.20.4

### Modloader (Fabric/Forge)

Fabric

### World-Preview Version

1.1.5

### Minecraft Logs

I posted the logs on the screenshot

### Additional Information

update the issue template

**Comment by Taiterio** [comment]
Thanks for the information! Fixed that in Version 1.3.1 with a scheduled release for tomorrow!
