### ISSUE TITLE
PV changing by y value

### ISSUE THREAD

**Issue by SettingDust** [caeruleusDraconis/world-preview#42]
### What happened?

The PV value is changing by Y. But it's fixed in noise router

### Minecraft Version

1.21

### Modloader (Fabric/Forge)

Fabric

### World-Preview Version

1.3.0

### Minecraft Logs

no

**Comment by SettingDust** [comment]
https://github.com/caeruleusDraconis/world-preview/blob/96b1f077af7ba6ea0cc1b3d0ad3854f0efd8f745/src/main/java/caeruleusTait/world/preview/client/gui/widgets/PreviewDisplay.java#L680

It's calced from weirdness instead of depth XD

**Comment by Taiterio** [comment]
Thanks for the heads up! We fixed the calculation and tomorrow we'll upload Version 1.3.1 in which it is fixed.
