### ISSUE TITLE
Weird issue loading the game

### ISSUE THREAD

**Issue by mpustovoi** [caeruleusDraconis/world-preview#46]
### What happened?

After updating to World Preview v1.3.1 and launching the game I got this screen:
![image](https://github.com/user-attachments/assets/3af02990-3f10-49be-8457-dbc7a89664a0)

### Minecraft Version

1.20.1

### Modloader (Fabric/Forge)

Forge

### World-Preview Version

1.3.1

### Minecraft Logs

[Logs](https://mclo.gs/plY8j9a) and [crash report](https://mclo.gs/NQyBPDY)
Idk why it says Vanilla crash report

### Additional Information

Also, I get some kind of Modrinth App issue with mod's version checker for updates. It's only on my Forge 1.20.1 instance and it's first time I see something like this.
It looks like the mod has a newer version while now it's latest 1.3.1:
![image](https://github.com/user-attachments/assets/a0d38de4-d63f-4c1f-a3d8-c41e3d963842)
But when I click 🔁, the version number disappears and a second after I can repeat this fake updating cycle:
![image](https://github.com/user-attachments/assets/94448028-1804-4fc3-ade9-dcb9aa533c8c)
Also, the App somehow doesn't sees that any version is installed, although on the left it's marked otherwise:
![image](https://github.com/user-attachments/assets/f7e913b1-fac8-4c1d-a9f8-ae311fcf0a8f)
So I can click here and once again download v1.3.1 but when I go to mod's versions page again it looks like it's not there.

**Comment by mpustovoi** [comment]
And also, I'm using the latest Forge mod loader 47.3.7 (it certainly won't be updated anymore)

**Comment by mpustovoi** [comment]
I think I've figured out what's going on. It should have been understood right away.
When I download the version for Forge 1.20.1, I download the file for Forge 1.21 instead.
It turns out that something got messed up on Modrinth, the wrong file is attached to the Forge 1.20.1 version:
![image](https://github.com/user-attachments/assets/d4d16c77-2a41-4f38-b536-8fe63e4c8054)

**Comment by caeruleusDraconis** [comment]
Tanks for reporting this. 

I have deleted the incorrect version from modrinth and added a new version with the correct file. I have bumped the version of the new release to 1.3.1.1, so modmanager should hopefully be able to detect that there is a new version and update.

**Comment by mpustovoi** [comment]
It worked. Thank you.
