### ISSUE TITLE
Conflicting Licenses

### ISSUE THREAD

**Issue by sandstripes** [caeruleusDraconis/world-preview#9]
Hello! I noticed that the License is marked as Apache-2.0 on the Modrinth page and in /src/main/resources/fabric.mod.json.fabric, but /LICENSE says CC0. Which license is it? It’s probably a good idea to correct it if it’s a mistake so people don’t put it under the wrong license

**Comment by caeruleusDraconis** [comment]
Thanks, the CC0 LICENSE was a copy paste error from the fabric mod template
